---
name: create sub-packages tag
on:
  release:
    types:
      - published
jobs:
  create-subpkg-tags:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        pkg:
          - amazonsns
          - amazonsqs
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: |
          git tag "${_tag}"
          git push origin "${_tag}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          _tag: ${{ matrix.pkg }}/${{ github.event.release.tag_name }}
